# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0009_auto_20171113_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='Arbitrary coupon value', max_digits=6, verbose_name='Value'),
        ),
    ]
