# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_auto_20170614_1450'),
        ('coupons', '0011_coupon_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='valid_products',
            field=models.ManyToManyField(blank=True, to='purchases.Product'),
        ),
    ]
