# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_auto_20170614_1450'),
        ('coupons', '0012_coupon_valid_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponuser',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchases.Order'),
        ),
    ]
