# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-22 15:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0013_couponuser_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
